name: Java CI with Gradle

on: [push,pull_request]

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Debug Docker login
        run: |
          echo "Username: ${{ secrets.DOCKER_USERNAME }}"
          echo "Testing Docker login..."
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          echo "Login successful!"
          
      - name: Test repository access
        run: |
          docker pull hello-world
          docker tag hello-world docker.io/sudarshan2504/test:latest
          docker push docker.io/sudarshan2504/test:latest
          echo "Test push successful!"

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: sudarshan2504/demoapp
          tag: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create repository if it doesn't exist
        run: |
            # This will fail if repo doesn't exist, but that's okay
            docker pull docker.io/sudarshan2504/demoapp:latest || echo "Repository might not exist yet"
          
  
